include $(THEOS)/makefiles/common.mk

APPLICATION_NAME = TriggrApp
TriggrApp_FILES = main.m
TriggrApp_FRAMEWORKS = UIKit
TriggrApp_CFLAGS = -fobjc-arc
TriggrApp_CODESIGN_FLAGS = -Sentitlements.plist
TriggrApp_INSTALL_PATH = /Applications

include $(THEOS_MAKE_PATH)/application.mk
