include $(THEOS)/makefiles/common.mk

TOOL_NAME = triggrd
triggrd_FILES = main.m
triggrd_CFLAGS = -fobjc-arc
triggrd_CODESIGN_FLAGS = -Sentitlements.plist
triggrd_INSTALL_PATH = /usr/libexec

include $(THEOS_MAKE_PATH)/tool.mk
